# Generated by Django 5.0.2 on 2024-02-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('cart_desc', models.CharField(max_length=250, null=True)),
                ('short_desc', models.CharField(max_length=1000, null=True)),
                ('long_desc', models.TextField(blank=True, null=True)),
                ('thumb', models.CharField(max_length=100, null=True)),
                ('price', models.FloatField()),
                ('stok', models.FloatField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
