# Generated by Django 5.0.2 on 2024-02-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_color_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumb',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
