# Generated by Django 5.0.2 on 2024-02-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('2xs', '2XS'), ('xs', 'XS'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('2xl', '2XL'), ('3xl', '3XL'), ('4xl', '4XL'), ('5xl', '5XL'), ('6xl', '6XL'), ('7xl', '7XL')], max_length=50, null=True),
        ),
    ]
