# Generated by Django 5.0.2 on 2024-02-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_color_alter_product_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='SKU',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
