# Generated by Django 5.0.2 on 2024-02-29 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_discount_product_discount_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount_id',
            new_name='discount',
        ),
    ]
