# Generated by Django 5.0.2 on 2024-02-29 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_discount_id_product_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='descrption',
            new_name='description',
        ),
    ]
