# Generated by Django 5.0.3 on 2024-03-11 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_category_product_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
    ]
