# Generated by Django 5.0.3 on 2024-04-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_color_active_color_created_at_color_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='code',
            field=models.CharField(default=12, max_length=50),
            preserve_default=False,
        ),
    ]
