# Generated by Django 5.0.3 on 2024-04-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_code_alter_stock_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
