# Generated by Django 5.0.3 on 2024-04-11 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_code_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.code'),
        ),
    ]
