# Generated by Django 5.0.3 on 2024-04-11 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_stock_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.code'),
            preserve_default=False,
        ),
    ]
